dependencies:
  build:
    - python:3.7.3

build_targets:
  - name: default
    dependencies:
      containers:
        redis:
          image: redis
          port_check:
            port: 6379
            timeout: 30
        splunk: 
          image: splunk/splunk:latest
          port_check:
            port: 8000
            timeout: 90
          environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_PASSWORD=password
    environment:
      - SPLUNK_IP={{ .Containers.IP "splunk" }}
      - REDIS_HOST={{ .Containers.IP "redis" }}
      - REDIS_PORT=6379
    commands:
      - pip install --upgrade pip
      - pip install poetry
      - pip install pytest coverage pytest-cov
      - pip install mock python-dateutil requests-futures lxml httplib2 urllib3 jinja2 boto3 docker
      - poetry config virtualenvs.create false
      - poetry config virtualenvs.in-project false
      - poetry install --no-root
      - bash run_services.sh
      - python run_tests.py tests/small tests/medium None None

ci:
  builds:
    - name: default
      build_target: default
